#include <stdio.h>
#include <eclipse.h>
#include <skb.h>

/* This .h file is generated by gdbus-codegen */
#include "Skb.h"

static gboolean
on_handle_add_fact(Skb * skeleton,
		   GDBusMethodInvocation * invocation, gchar * fact)
{
	char out[128];
//	g_message("Add fact %s", fact);

	if (!skb_add_fact_my(fact))
		sprintf(out, "OK");
	else
		sprintf(out, "Eclipse returned error");
	skb_complete_add_fact(skeleton, invocation, out);
}

static gboolean
on_handle_query(Skb * skeleton,
		GDBusMethodInvocation * invocation, gchar * query)
{
	static struct skb_query_state st;
	char str[1024];		//XXX
	int res;

//	g_message("SKB query: %s", query);
	res = execute_query(query, &st);

	if (res == 0)
		sprintf(str, "Yes. : %s", st.output_buffer);
	else if (res == 1)
		sprintf(str, "No. : %s", st.output_buffer);
	else
		sprintf(str, "Error. : %s", st.error_buffer);

	skb_complete_query(skeleton, invocation, str);
}

static void
on_name_acquired(GDBusConnection * connection,
		 const gchar * name, gpointer user_data)
{
	Skb *skeleton;

	skeleton = skb_skeleton_new();
	g_signal_connect(skeleton,
			 "handle-add-fact", G_CALLBACK(on_handle_add_fact),
			 NULL);

	g_signal_connect(skeleton,
			 "handle-query", G_CALLBACK(on_handle_query), NULL);
	g_message("name aquired");
	g_dbus_interface_skeleton_export(G_DBUS_INTERFACE_SKELETON(skeleton),
					 connection, "/org/freedesktop/Skb",
					 NULL);
}

static void
on_name_lost (GDBusConnection *connection,
              const gchar     *name,
              gpointer         user_data)
{
  g_print ("Lost the name %s on the session bus\n", name);
  g_main_loop_quit(user_data);
}

void main(void)
{
	GMainLoop *loop;
	guint owner_id;

	skb_init();

	loop = g_main_loop_new(NULL, FALSE);

	owner_id = g_bus_own_name(G_BUS_TYPE_SESSION,
		       "org.freedesktop.Skb",
		       G_BUS_NAME_OWNER_FLAGS_NONE,
		       NULL, on_name_acquired, on_name_lost, loop, NULL);

	g_main_loop_run(loop);

	g_bus_unown_name (owner_id);
}
